dist: xenial
language: go
go:
  - 1.13.x

go_import_path: github.com/application-stacks/runtime-component-operator
env:
  - GO111MODULE=on

services:
  - docker

stages:
  - name: build
    if: fork = false
  - name: build manifest
    if: fork = false

jobs:
  include:
    - name: Build image on amd64
      stage: build
      os: linux
      arch: amd64
      script:
        - make build-multiarch-image
        - make build-manifest
    - name: Build image on ppc64le
      os: linux
      arch: ppc64le
      script:
        - make build-multiarch-image
        - make build-manifest
    - name: Build image on s390x
      os: linux
      arch: s390x
      script:
        - make build-multiarch-image
        - make build-manifest
    ## in case there were concurrency issues with building manifest lists
    ## in previous steps, create FAT manifests one last time
    - name: Verify manifest lists
      stage: build manifest
      script: make build-manifest
