apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: rco-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rco-leader-election-role
subjects:
- kind: ServiceAccount
  name: rco-sa
  namespace: rco-system
