# permissions for end users to view runtimeoperations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: runtimeoperation-viewer-role
rules:
- apiGroups:
  - app.stacks
  resources:
  - runtimeoperations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.stacks
  resources:
  - runtimeoperations/status
  verbs:
  - get
