# permissions for end users to view runtimecomponents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: runtimecomponent-viewer-role
rules:
- apiGroups:
  - rc.app.stacks
  resources:
  - runtimecomponents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rc.app.stacks
  resources:
  - runtimecomponents/status
  verbs:
  - get
