# permissions for end users to edit runtimeoperations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: runtimeoperation-editor-role
rules:
- apiGroups:
  - app.stacks
  resources:
  - runtimeoperations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.stacks
  resources:
  - runtimeoperations/status
  verbs:
  - get
