apiVersion: app.stacks/v1beta1
kind: RuntimeComponent
metadata:
  name: runtimecomponent-sample
spec:
  # Add fields here
  applicationImage: registry.connect.redhat.com/ibm/open-liberty-samples:springPetClinic
