apiVersion: rc.app.stacks/v1beta2
kind: RuntimeComponent
metadata:
  name: runtimecomponent-sample
spec:
  # Add fields here
  applicationImage: registry.connect.redhat.com/ibm/open-liberty-samples:springPetClinic
  expose: true
  replicas: 1
  service:
    port: 9080